export const divisions = [
  "Bengaluru Division",
  "Mysuru Division",
  "Belagavi Division",
  "Kalaburagi Division",
];

export const districtsByDivision: Record<string, string[]> = {
  "Bengaluru Division": [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Chikkaballapura",
    "Chitradurga",
    "Davanagere",
    "Kolar",
    "Ramanagara",
    "Shimoga",
    "Tumakuru",
  ],
  "Mysuru Division": [
    "Chamarajanagar",
    "Chikkamagaluru",
    "Dakshina Kannada",
    "Hassan",
    "Kodagu",
    "Mandya",
    "Mysuru",
    "Udupi",
  ],
  "Belagavi Division": [
    "Bagalkot",
    "Belagavi",
    "Dharwad",
    "Gadag",
    "Haveri",
    "Uttara Kannada",
  ],
  "Kalaburagi Division": [
    "Ballari",
    "Bidar",
    "Kalaburagi",
    "Koppal",
    "Raichur",
    "Vijayapura",
    "Yadgir",
  ],
};

export const taluksByDistrict: Record<string, string[]> = {
  "Bengaluru Urban": [
    "Bengaluru North",
    "Bengaluru South",
    "Bengaluru East",
    "Anekal",
    "Yelahanka",
  ],
  "Bengaluru Rural": [
    "Devanahalli",
    "Doddaballapura",
    "Hosakote",
    "Nelamangala",
  ],
  "Chikkaballapura": [
    "Chikkaballapura",
    "Chintamani",
    "Gauribidanur",
    "Gudibanda",
    "Bagepalli",
    "Sidlaghatta",
  ],
  "Chitradurga": [
    "Chitradurga",
    "Challakere",
    "Hiriyur",
    "Holalkere",
    "Hosadurga",
    "Molakalmuru",
  ],
  "Davanagere": [
    "Davanagere",
    "Channagiri",
    "Harihara",
    "Honnali",
    "Jagaluru",
    "Harapanahalli",
  ],
  "Kolar": [
    "Kolar",
    "Bangarpet",
    "KGF",
    "Malur",
    "Mulbagal",
    "Srinivaspur",
  ],
  "Ramanagara": [
    "Ramanagara",
    "Channapatna",
    "Kanakapura",
    "Magadi",
  ],
  "Shimoga": [
    "Shimoga",
    "Bhadravathi",
    "Hosanagara",
    "Sagar",
    "Shikarpur",
    "Soraba",
    "Thirthahalli",
  ],
  "Tumakuru": [
    "Tumakuru",
    "Gubbi",
    "Koratagere",
    "Kunigal",
    "Madhugiri",
    "Pavagada",
    "Sira",
    "Tiptur",
    "Turuvekere",
    "Chikkanayakanahalli",
  ],
  "Chamarajanagar": ["Chamarajanagar", "Gundlupet", "Kollegal", "Yelandur"],
  "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Koppa", "Mudigere", "Narasimharajapura", "Sringeri", "Tarikere"],
  "Dakshina Kannada": ["Mangaluru", "Bantwal", "Belthangady", "Puttur", "Sullia"],
  "Hassan": ["Hassan", "Alur", "Arkalgud", "Arsikere", "Belur", "Channarayapatna", "Holenarasipura", "Sakleshpur"],
  "Kodagu": ["Madikeri", "Somwarpet", "Virajpet"],
  "Mandya": ["Mandya", "Krishnarajpet", "Maddur", "Malavalli", "Nagamangala", "Pandavapura", "Srirangapatna"],
  "Mysuru": ["Mysuru", "Heggadadevankote", "Hunsur", "Krishnarajanagara", "Nanjangud", "Periyapatna", "Tirumakudalu Narasipura"],
  "Udupi": ["Udupi", "Kundapura", "Karkala"],
  "Bagalkot": ["Bagalkot", "Badami", "Bilgi", "Hungund", "Jamkhandi", "Mudhol"],
  "Belagavi": ["Belagavi", "Athani", "Bailhongal", "Chikkodi", "Gokak", "Hukkeri", "Khanapur", "Raibag", "Ramdurg", "Savadatti"],
  "Dharwad": ["Dharwad", "Hubballi", "Kalghatgi", "Kundgol", "Navalgund"],
  "Gadag": ["Gadag", "Mundargi", "Nargund", "Ron", "Shirahatti"],
  "Haveri": ["Haveri", "Byadgi", "Hanagal", "Hirekerur", "Ranebennur", "Savanur", "Shiggaon"],
  "Uttara Kannada": ["Karwar", "Ankola", "Bhatkal", "Haliyal", "Honavar", "Joida", "Kumta", "Mundgod", "Siddapur", "Sirsi", "Yellapur"],
  "Ballari": ["Ballari", "Hadagalli", "Hagaribommanahalli", "Hospet", "Kudligi", "Sandur", "Siruguppa"],
  "Bidar": ["Bidar", "Aurad", "Basavakalyan", "Bhalki", "Humnabad"],
  "Kalaburagi": ["Kalaburagi", "Afzalpur", "Aland", "Chincholi", "Chittapur", "Jewargi", "Sedam"],
  "Koppal": ["Koppal", "Gangavathi", "Kushtagi", "Yelburga"],
  "Raichur": ["Raichur", "Devadurga", "Lingasugur", "Manvi", "Sindhanur"],
  "Vijayapura": ["Vijayapura", "Basavana Bagewadi", "Indi", "Muddebihal", "Sindgi"],
  "Yadgir": ["Yadgir", "Shahapur", "Shorapur"],
};

export const allDistricts = Object.values(districtsByDivision).flat();

export const citiesByDistrict: Record<string, string[]> = {
  "Bengaluru Urban": ["Bengaluru"],
  "Bengaluru Rural": ["Devanahalli", "Doddaballapura", "Hosakote", "Nelamangala"],
  "Mysuru": ["Mysuru", "Nanjangud", "Hunsur"],
  "Dakshina Kannada": ["Mangaluru", "Puttur", "Bantwal"],
  "Belagavi": ["Belagavi", "Gokak", "Chikkodi"],
  "Kalaburagi": ["Kalaburagi", "Sedam", "Afzalpur"],
  "Ballari": ["Ballari", "Hospet"],
  "Dharwad": ["Hubballi", "Dharwad"],
};
